[mongodb]
mongodb-dev.109v.store

[catalogue]
catalogue-dev.109v.store

[redis]
redis-dev.109v.store

[user]
user-dev.109v.store

[cart]
cart-dev.109v.store

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.109v.store
CATALOGUE_HOST=catalogue-dev.109v.store
REDIS_HOST=redis-dev.109v.store
USER_HOST=user-dev.109v.store

